apiVersion: v1
kind: Secret
metadata:
  name: github-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:tpSpace/infra.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACBVdlZJAAvq7RpCzkqY+ri7mAPuYcgu0VmMZP1gwHC48wAAAJh/4jkBf+I5
    AQAAAAtzc2gtZWQyNTUxOQAAACBVdlZJAAvq7RpCzkqY+ri7mAPuYcgu0VmMZP1gwHC48w
    AAAEAtwdr8OJvp6vFo2/cQC71omIFeUMOL9UMrxixCg8l0K1V2VkkAC+rtGkLOSpj6uLuY
    A+5hyC7RWYxk/WDAcLjzAAAADmFyZ28tY2QtYWNjZXNzAQIDBAUGBw==
    -----END OPENSSH PRIVATE KEY-----
