apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-seed
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: seed
          image: ghcr.io/tpspace/thesis-be:latest
          command: ["sh", "-c", "npx prisma migrate deploy && npm run seed"]
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: db-credentials
      imagePullSecrets:
        - name: ghcr-secret
