apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "conghoaxa"
  POSTGRES_DB: "thesisdb"
  DATASOURCE_URL: "postgresql://postgres:conghoaxa@postgres:5432/thesisdb"
  GHCT_TOKEN: "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"
  REACT_APP_API_URL: "http://backend:4000"
