apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: conghoaxa
  POSTGRES_DB: neondb

  DATASOURCE_URL: postgresql://neondb_owner:npg_8MiUZwEoF0Yz@ep-lingering-cell-a1ftun6w-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require

  REACT_APP_API_URL: http://backend:4000
