apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  POSTGRES_USER: "${DB_USER}"
  POSTGRES_PASSWORD: "${DB_PASSWORD}"
  POSTGRES_DB: "${DB_NAME}"
  DATASOURCE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}"
  GHCT_TOKEN: "${GHCR_TOKEN}"
  REACT_APP_API_URL: "http://backend:4000"
