apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "securepw"
  POSTGRES_DB: "thesisdb"
  DATASOURCE_URL: "postgresql://postgres:securepw@postgres:5432/thesisdb"
  GHCT_TOKEN: "yourtoken"
  REACT_APP_API_URL: "http://backend:4000"
