apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: thesis
  namespace: argocd
spec:
  description: Thesis Project for Frontend and Backend Applications
  sourceRepos:
    - git@github.com:tpSpace/infra.git
    - git@github.com:tpSpace/thesis-fe.git
    - git@github.com:tpSpace/thesis-be.git
  destinations:
    - namespace: my-thesis
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
