apiVersion: v1
kind: Secret
metadata:
  name: postgres-llm-secret
  namespace: my-thesis
type: Opaque
stringData:
  db_name: grading_service
  db_username: grading_user
  db_password: GradingService123!
  connection_string: postgresql://grading_user:GradingService123!@postgres-llm:5432/grading_service
