apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: my-thesis
  labels:
    app: rabbitmq
    component: message-broker
spec:
  serviceName: rabbitmq
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
        component: message-broker
    spec:
      # Security context for better container security
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999

      containers:
        - name: rabbitmq
          image: rabbitmq:3.12-management

          # Ports configuration
          ports:
            - containerPort: 5672
              name: amqp
              protocol: TCP
            - containerPort: 15672
              name: management
              protocol: TCP
            - containerPort: 15692
              name: prometheus
              protocol: TCP

          # Resource configuration - slightly increased for stability
          resources:
            requests:
              cpu: "200m" # Increased from 100m
              memory: "512Mi" # Increased from 256Mi
            limits:
              cpu: "1000m" # Increased from 500m
              memory: "1Gi" # Increased from 512Mi

          # Environment variables
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: user
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
            - name: RABBITMQ_ERLANG_COOKIE
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: erlang-cookie

            # Additional environment variables for better container behavior
            - name: RABBITMQ_NODE_TYPE
              value: stats
            - name: RABBITMQ_NODENAME
              value: rabbit@rabbitmq-0.rabbitmq.my-thesis.svc.cluster.local
            - name: RABBITMQ_USE_LONGNAME
              value: "true"
            - name: RABBITMQ_CONFIG_FILE
              value: /etc/rabbitmq/rabbitmq.conf
            - name: RABBITMQ_MNESIA_BASE
              value: /var/lib/rabbitmq/mnesia
            - name: RABBITMQ_LOGS
              value: "-"
            - name: RABBITMQ_SASL_LOGS
              value: "-"

          # Volume mounts
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq/mnesia
            - name: rabbitmq-config
              mountPath: /etc/rabbitmq/rabbitmq.conf
              subPath: rabbitmq.conf
              readOnly: true
            - name: rabbitmq-config
              mountPath: /etc/rabbitmq/enabled_plugins
              subPath: enabled_plugins
              readOnly: true
            # Additional mount for better temp file handling
            - name: tmp-volume
              mountPath: /tmp

          # Improved health checks
          livenessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - ping
                - -q
            initialDelaySeconds: 120 # Increased from 60 for safer startup
            periodSeconds: 30 # Increased from 20
            timeoutSeconds: 15 # Increased from 10
            failureThreshold: 3
            successThreshold: 1

          readinessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - check_port_connectivity
                - -q
            initialDelaySeconds: 30 # Increased from 20
            periodSeconds: 15 # Increased from 10
            timeoutSeconds: 10 # Increased from 5
            failureThreshold: 3
            successThreshold: 1

          # Startup probe for initial container startup
          startupProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - ping
                - -q
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 12 # 2 minutes max startup time
            successThreshold: 1

          # Lifecycle hooks for graceful shutdown
          lifecycle:
            preStop:
              exec:
                command:
                  - rabbitmq-upgrade
                  - drain

      # Pod-level configurations
      terminationGracePeriodSeconds: 60

      # Volumes
      volumes:
        - name: rabbitmq-config
          configMap:
            name: rabbitmq-config
            defaultMode: 0644
        - name: tmp-volume
          emptyDir:
            sizeLimit: 1Gi

      # Pod disruption settings
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - rabbitmq
                topologyKey: kubernetes.io/hostname

  # Volume claim templates
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-data
        labels:
          app: rabbitmq
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 8Gi
        # Optional: specify storage class for better performance
        # storageClassName: ssd-retain
