apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: my-thesis
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
      name: amqp
    - port: 15672
      targetPort: 15672
      protocol: TCP
      name: management
  type: ClusterIP
---
# Optional: External access to management UI (remove if not needed)
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management-external
  namespace: my-thesis
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - port: 15672
      targetPort: 15672
      protocol: TCP
      name: management
  type: LoadBalancer
